### ISSUE TITLE
To Start A Jesse import candles need to dance with bubn

### ISSUE THREAD

**Issue by xsa-dev** [jesse-ai/jesse-stack-docker#5]
After this on readme: **[4. Into Jesse container, Import the candle history](https://github.com/jesse-ai/jesse-stack-docker#4-into-jesse-container-import-the-candle-history)**

After command 
`jesse import-candles Binance BTCUSDT 2020-06-01`

I get an error <> and in order for it to pass needed to install for ubuntu from [Environment Setup](https://github.com/jesse-ai/docs/blob/master/docs/getting-started/environment-setup.md). 

By this command:
`sh -c "$(curl -fsSL https://raw.githubusercontent.com/jesse-ai/stack-installer/master/ubuntu-18.04.sh)"`

and `apt update && apt install curl -y` before

After that, the error goes away.

**Comment by julesGoullee** [comment]
Fixed
