### ISSUE TITLE
Can't use Docker Desktop Start button on Windows. 

### ISSUE THREAD

**Issue by cryptocoinserver** [jesse-ai/jesse-stack-docker#7]
In Docker Desktop Windows there is this start and stop button for each stack and container in the dashboard.

With "docker-compose run jesse bash" all starts up and works. Docker Desktop then lists the stack with its containers below. 

The issue: Starting it from the dashboard with the start button of the stack doesn't work. Instead, it fires up a new instance of the jesse container (without "run" in the name), which fails to start. It says EXITED (0). Can't see logs. Starting each container individually works (the start buttons on container level). So only the start button of the whole stack doesn't behave right.

**Comment by julesGoullee** [comment]
I will recommend starting the process from the command line. To start the jesse container from the UI anyway use the `cli` button in place of play, it open a terminal with an interactive shell, type `bash` then you're in the same state as the compose command line
